name = "anishsingla-website"
compatibility_date = "2025-12-26"
workers_dev=true
preview_urls= true

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"

[[routes]]
pattern = "anishsingla.xyz"
custom_domain = true
